### ISSUE TITLE
RE: BBAI, Compatibility Layer, and Setting Up/PWM

### ISSUE THREAD

**Issue by silver2row** [beagleboard/BeagleBoard-DeviceTrees#29]
Hello,

I followed the instructions here: https://deepaklorkhatri.me/GSoC2020_BeagleBoard.org/

- First, I followed those instructions with this image and kernel:
    BeagleBoard.org Debian Buster IoT Image 2020-11-16
    4.19.94-ti-r56

- Secondly, I looked for pwm in /sys/class/pwm/, /dev/pwm/, and /dev/bone/pwm/. 
    I have not been able to get the pwm peripheral located yet

...

Please advise me on what to tackle next. I have tried to clone w/ git many things.

https://github.com/beagleboard/bb.org-overlays

and...

https://github.com/lorforlinux/bb.org-overlays

and...

https://github.com/beagleboard/BeagleBoard-DeviceTrees

I tried make, adding BONE-PWM1.dtbo to /boot/uEnv.txt, and I even tried different git checkout commands.

Is there an easier way to test these Bone_Bus capabilities? I am asking b/c I have a BBAI and I have been unable to make this work just yet.

Seth

P.S. I forgot to mention that I tried the instructions on this site too: https://deepaklorkhatri.me/GSoC2020_BeagleBoard.org/2020/07/22/using-bone-pwm/. 

Also: I put the am5729-beagleboneai.dtb in the uEnv.txt file at the /boot/ dir. I put the BONE-PWM1.dtbo under External Capes in that same file. I now have a pwmchip0 under /sys/class/pwm/pwmchip0/.

**Comment by RobertCNelson** [comment]
Please include output off..

sudo /opt/scripts/tools/version.sh

**Comment by silver2row** [comment]
Hello Sir,

I know I seem to wonder a lot. I got the /sys/class/pwm/pwm-2:0 interface to work w/ the BBAI so far on p9.14.

Anyway...here is the output of sudo /opt/scripts/tools/version.sh:

https://pastebin.com/6Z06D9Cf

Seth

P.S. Please let me know if you need anything else.

**Comment by silver2row** [comment]
Hello Sir,

Seth here. Um, I used a lib. in python to handle PWM onboard the BBAI so far. It worked!

...

Anyway, I do not see the entry in /dev/pwm/ yet. I will keep trying. 

Seth

P.S. Please just let me know if you need any more info. from me.

**Comment by RobertCNelson** [comment]
/sys/class/pwm/ is the correct location

**Comment by silver2row** [comment]
Hello,

Thank you for replying. I got it up and running w/ a pwm instance doing the on/off routine for p9.14 on the BBAI. I am learning slowly about this new idea.

Seth

P.S. I can close this issue if it is of no concern...let me know.
